### ISSUE TITLE
FunctionCall does not have the corresponding parameters.

### ISSUE THREAD

**Issue by qq312888991** [betalgo/openai#459]
After updating to the latest version, the "FunctionCall" was replaced with "Tools", and the required parameters have been marked. However, when calling the interface, the tool.FunctionCall does not have the corresponding parameters.

![image](https://github.com/betalgo/openai/assets/4046072/4e0b26ea-a6a0-4f62-b574-7491c337285f)

**Comment by qq312888991** [comment]
Sorry, I understand. In the【OpenAI.Playground/TestHelpers/ChatCompletionTestHelper.cs] There is an example, thank you

**Comment by David-Buyer** [comment]
This happens because the logic about reassembling Function Calls data in chat completations -> stream mode, was not refactored to reflect the same behavior with the newest API model by using Tool Calls. I made a pull request with the refactored logic to attempt resuming the previous behavior with Tool Calls API model:

https://github.com/betalgo/openai/pull/463

In every case you can do it by yourself, following the example mentioned above.
